#!/usr/bin/env bash
# The script displaying information of /etc/passwd
while IFS=: read -r username _ user_id _ _ _ home_dir _; do
    echo "Username: $username, User ID: $user_id, Home Directory: $home_dir"
done < /etc/passwd
