#!/usr/bin/env bash
#The script to group visitors by IP and HTTP status code, and display occurrences

awk '{print $1, $9}' apache-access.log | sort -V | uniq -c | sort -n | perl -e 'print reverse <>'
