#!/usr/bin/env bash
# The script displaying "Best School" 10 times using while loop and display a special message on the 9th iteration
count=1
while [ $count -le 10 ]
do
if [ $count -eq 9 ]; then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
count=$((count + 1))
done
