#!/usr/bin/env bash
# The script that manages 'manage_my_process' script
pid_file="/var/run/my_process.pid"
process_script="./manage_my_process"

start_process() {
    if [ -f "$pid_file" ]; then
        echo "manage_my_process is already running"
    else
        $process_script &
        echo $! > "$pid_file"
        echo "manage_my_process started"
    fi
}

stop_process() {
    if [ -f "$pid_file" ]; then
        kill "$(cat "$pid_file")"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart_process() {
    stop_process
    start_process
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
