#!/usr/bin/env bash
# 8-beheaded_process script

# Find the PID of the 7-highlander process
PID=$(pgrep -f 7-highlander)

if [ -n "$PID" ]; then
    # Forcefully kill the process
    kill -9 "$PID" >/dev/null 2>"&1"
fi
